# -*- coding: utf-8 -*-
"""FatimaQurban_DBInsertion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XLhgU5bJP10tfNHRLYvJHVYHn4xtusw9

# Database Insertion
"""

#!pip install pymongo

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df=pd.read_csv('/content/drive/My Drive/FatimaQurban_PCN_Internship/PCNInternship_FatimaQurban_Task0/ebay_psychology_books.csv')

df.shape
df.head()

data=df.to_dict(orient='records')
print(data)

import pymongo

# Get the MongoDB connection string from the environment variable

# Connect to MongoDB Atlas
Client=pymongo.MongoClient("mongodb+srv://ebayData:Fast2021@cluster0.kl8fsce.mongodb.net/")

# Selecting the database
db=Client["Ebay_ScrappedData"]

# Selecting the collection
collection = db["Ebay-data"]

# Insert the data
collection.insert_many(data)

print("Data inserted successfully!")

